feat: adiciona validacao mensagem

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,32 +1,94 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
 jobs:
-  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
   build-and-test:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
-    # Be sure to update the tag on this image to a more stable version, using latest can result in unstable builds.
     docker:
       - image: mcr.microsoft.com/dotnet/sdk:5.0
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
     steps:
-      # Checkout the code as the first step.
-      - checkout
-      # Then simply use the dotnet container as you'd expect and run your tests
       - checkout
       - run: dotnet restore
       - run: dotnet build
       - run: dotnet run
 
-# Invoke jobs via workflows
-# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+  validate-message:
+    parameters:
+      pattern:
+        description: "Regex pattern"
+        type: string
+        default: ""
+
+      error_message:
+        description: "The message displayed when message validation is failed"
+        type: string
+        default: "Invalid commit message"
+
+    executor:
+      name: circleci-node-latest
+
+    working_directory: /tmp/git_commit-message-validator
+
+    steps:
+      - checkout
+      - validate:
+          pattern: <<parameters.pattern>>
+          error_message: <<parameters.error_message>>
+
+commands:
+  validate:
+    parameters:
+      pattern:
+        description: "Regex pattern"
+        type: string
+        default: ""
+
+      error_message:
+        description: "The message displayed when message validation is failed"
+        type: string
+        default: "Invalid commit message"
+
+    steps:
+      - when:
+          condition: <<parameters.pattern>>
+          steps:
+            - run:
+                name: Get commit message
+                command: |
+                  echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
+                  source $BASH_ENV
+
+            - run:
+                name: Create message validator
+                command: |
+                  echo "var commit_message = \"$COMMIT_MESSAGE\";" > orbs_git_commit-message-validator.js
+                  echo "var pattern = \"<<parameters.pattern>>\";" >> orbs_git_commit-message-validator.js
+
+                  echo "if (commit_message.match(pattern)) {" >> orbs_git_commit-message-validator.js
+                  echo "  console.log(\"commit message is in valid format\");" >> orbs_git_commit-message-validator.js
+                  echo "  return true;" >> orbs_git_commit-message-validator.js
+                  echo "} else {" >> orbs_git_commit-message-validator.js
+                  echo "  console.log(\"<<parameters.error_message>>\");" >> orbs_git_commit-message-validator.js
+                  echo "  throw \"<<parameters.error_message>>\";" >> orbs_git_commit-message-validator.js
+                  echo "};" >> orbs_git_commit-message-validator.js
+
+            - run:
+                name: Validate commit messages
+                command: |
+                  node orbs_git_commit-message-validator.js
+
+      - unless:
+          condition: <<parameters.pattern>>
+          steps:
+            - run:
+                name: Show error msg and return false
+                command: |
+                  echo "Error: No regex pattern supplied. exit 1."
+                  exit 1
+executors:
+  circleci-node-latest:
+    docker:
+      - image: circleci/node:10
+
 workflows:
-  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  sample: 
     jobs:
       - build-and-test
